# Generated by Django 5.2.16 on 2026-07-23 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nhtsa_incident_report', 'NHTSA Incident Report'), ('openalex_work', 'OpenAlex Work')], max_length=32)),
                ('source_id', models.TextField()),
                ('raw_data', models.JSONField()),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('time_occurred', models.DateTimeField(null=True)),
                ('time_reported', models.DateTimeField(null=True)),
                ('time_ingested', models.DateTimeField()),
                ('time_judged', models.DateTimeField(null=True)),
                ('time_reviewed', models.DateTimeField(null=True)),
                ('animal_type', models.CharField(choices=[('farmed', 'Farmed'), ('wild', 'Wild'), ('companion', 'Companion'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=9)),
                ('animal_species', models.TextField(blank=True, default='')),
                ('animal_count', models.IntegerField(default=-1)),
                ('harm_type', models.TextField(blank=True, default='')),
                ('harm_description', models.TextField(blank=True, default='')),
                ('ai_system', models.TextField(blank=True, default='')),
                ('ai_system_manufacturer', models.TextField(blank=True, default='')),
                ('city', models.TextField(blank=True, default='')),
                ('country', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=8)),
                ('confidence', models.IntegerField(default=0)),
                ('llm_reasoning', models.TextField(blank=True, default='')),
                ('llm_model', models.TextField(blank=True, default='')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_source_sourceid')],
            },
        ),
    ]
