# Generated by Django 5.2.16 on 2026-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='time_hydrated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('llm_relevant', 'LLM deemed relevant'), ('llm_rejected', 'LLM rejected for lack of relevancy'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=12),
        ),
    ]
