# Generated by Django 5.2.16 on 2026-07-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_incidentreport_time_hydrated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SourceIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32, unique=True)),
                ('single_ingestion', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
