# Generated by Django 5.2.16 on 2026-07-29 20:46

from django.db import migrations


def seed_sources(apps, schema_editor):
    SourceIngestion = apps.get_model("dash", "SourceIngestion")
    SourceIngestion.objects.create(
        source="nhtsa_incident_report",
        single_ingestion=True,
    )
    SourceIngestion.objects.create(
            source="openalex_work",
            single_ingestion=False,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_pipelinerun_sourceingestion'),
    ]

    operations = [
        migrations.RunPython(seed_sources),
    ]
