# Generated by Django 5.2.16 on 2026-09-14 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_initial_db_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='source',
            field=models.CharField(choices=[('nhtsa_incident_report', 'NHTSA Incident Report'), ('openalex_work', 'OpenAlex Work'), ('user_submitted', 'User Submitted')], max_length=32),
        ),
    ]
